services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: "host"

    environment:
      TZ: "Europe/Amsterdam"
      WEBPASSWORD: "D0nk3rbr!l95"
      PIHOLE_DNS_: "127.0.0.1#5053"
      DNSMASQ_LISTENING: "all"
      ServerIP: "192.168.2.40"
      VIRTUAL_HOST: "pi.hole"
      SSL_CERT: "/etc/ssl/certs/pihole.crt"
      SSL_KEY: "/etc/ssl/private/pihole.key"

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
      - /etc/ssl/certs/pihole.crt:/etc/ssl/certs/pihole.crt:ro
      - /etc/ssl/private/pihole.key:/etc/ssl/private/pihole.key:ro

  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro
